# Generated by Django 2.2 on 2021-04-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_hello', '0002_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='fullname',
            new_name='username',
        ),
    ]
