# Generated by Django 2.2 on 2021-05-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_hello', '0005_auto_20210503_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'creature'},
        ),
    ]
