# Generated by Django 3.2.2 on 2021-05-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=10)),
                ('s_email', models.CharField(max_length=10)),
                ('s_code', models.CharField(max_length=5)),
                ('s_points', models.IntegerField(default=0)),
            ],
        ),
    ]
