language: python

python:
    -"3.8.1"
  
env:
    - SECRET_KEY='TEST'
  
services:
    - postgresql

install:
    - pipenv install

script:
    - coverage run --source='authentication' manage.py test & coverage report

after_success:
    - codecov
