# Generated by Django 3.2.2 on 2021-05-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mtm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='medal',
            field=models.CharField(blank=True, choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze'), ('WIN', 'Win'), ('LOSE', 'Lose')], max_length=10),
        ),
    ]
